//! Re:PhiEdit json format
//!
//! Credit: https://teamflos.github.io/phira-docs/chart-standard/chart-format/rpe

use num::{Num, Rational32};
use phichain_chart::beat::Beat;
use phichain_chart::easing::Easing;
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(Default, Debug, Clone, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum RpeNoteKind {
    #[default]
    Tap = 1,
    Drag = 4,
    Hold = 2,
    Flick = 3,
}

// generated by https://transform.tools/json-to-rust-serde
#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RpeBeat(pub i32, pub i32, pub i32);

impl From<RpeBeat> for Beat {
    fn from(val: RpeBeat) -> Self {
        Beat::new(val.0, Rational32::new(val.1, val.2))
    }
}

impl From<Beat> for RpeBeat {
    fn from(value: Beat) -> Self {
        RpeBeat(value.beat(), value.numer(), value.denom())
    }
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeChart {
    #[serde(rename = "BPMList")]
    pub bpm_list: Vec<RpeBpmPoint>,
    #[serde(rename = "META")]
    pub meta: RpeMeta,
    pub judge_line_list: Vec<RpeJudgeLine>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeBpmPoint {
    pub bpm: f32,
    pub start_time: RpeBeat,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeMeta {
    #[serde(rename = "RPEVersion")]
    pub rpe_version: i32,
    pub background: String,
    pub charter: String,
    pub composer: String,
    pub id: String,
    pub level: String,
    pub name: String,
    pub offset: i32,
    pub song: String,
}

fn deserialize_event_layers<'de, D>(deserializer: D) -> Result<Vec<RpeEventLayer>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let layers: Vec<Option<RpeEventLayer>> = Vec::deserialize(deserializer)?;
    Ok(layers.into_iter().flatten().collect())
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeJudgeLine {
    /// The name of the line
    #[serde(rename = "Name")]
    pub name: String,

    /// The parent line; -1 indicates no parent
    pub father: i32,
    /// Does the child line inherit the parent line's rotation angle
    #[serde(default, rename = "rotateWithFather")]
    pub rotate_with_father: bool,
    /// Before a certain version, the field will be `null` if there's no events in this layer (ref: https://teamflos.github.io/phira-docs/chart-standard/chart-format/rpe/judgeLine.html)
    #[serde(default, deserialize_with = "deserialize_event_layers")]
    pub event_layers: Vec<RpeEventLayer>,
    #[serde(default)]
    pub notes: Vec<RpeNote>,
    pub num_of_notes: usize,
    /// Attach this line to a UI element
    /// Lines with this field are not actual lines but UI control lines
    #[serde(default, rename = "attachUI")]
    pub attach_ui: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeEventLayer {
    #[serde(default)]
    pub alpha_events: Vec<RpeCommonEvent<i32>>,
    #[serde(default, rename = "moveXEvents")]
    pub move_x_events: Vec<RpeCommonEvent<f32>>,
    #[serde(default, rename = "moveYEvents")]
    pub move_y_events: Vec<RpeCommonEvent<f32>>,
    #[serde(default)]
    pub rotate_events: Vec<RpeCommonEvent<f32>>,
    #[serde(default)]
    pub speed_events: Vec<RpeSpeedEvent>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeCommonEvent<T: Num> {
    pub bezier: i32,
    #[serde(rename = "bezierPoints")]
    pub bezier_points: [f32; 4],
    pub easing_type: i32,
    pub end: T,
    pub end_time: RpeBeat,
    pub start: T,
    pub start_time: RpeBeat,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeSpeedEvent {
    pub end: f32,
    pub end_time: RpeBeat,
    pub start: f32,
    pub start_time: RpeBeat,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpeNote {
    pub above: i32,
    pub end_time: RpeBeat,
    pub position_x: f32,
    pub speed: f32,
    pub start_time: RpeBeat,
    pub size: f32,         // ignored
    pub visible_time: f32, // ignored
    #[serde(rename = "type")]
    pub kind: RpeNoteKind,
    /// 1 => fake note, other values => real note
    #[serde(default, rename = "isFake")]
    pub is_fake: i32,
}

pub static RPE_EASING: [Easing; 30] = [
    Easing::Linear,
    Easing::Linear,
    Easing::EaseOutSine,
    Easing::EaseInSine,
    Easing::EaseOutQuad,
    Easing::EaseInQuad,
    Easing::EaseInOutSine,
    Easing::EaseInOutQuad,
    Easing::EaseOutCubic,
    Easing::EaseInCubic,
    Easing::EaseOutQuart,
    Easing::EaseInQuart,
    Easing::EaseInOutCubic,
    Easing::EaseInOutQuart,
    Easing::EaseOutQuint,
    Easing::EaseInQuint,
    Easing::EaseOutExpo,
    Easing::EaseInExpo,
    Easing::EaseOutCirc,
    Easing::EaseInCirc,
    Easing::EaseOutBack,
    Easing::EaseInBack,
    Easing::EaseInOutCirc,
    Easing::EaseInOutBack,
    Easing::EaseOutElastic,
    Easing::EaseInElastic,
    Easing::EaseOutBounce,
    Easing::EaseInBounce,
    Easing::EaseInOutBounce,
    Easing::EaseInOutElastic,
];
