use phichain_chart::curve_note_track::generate_notes;
use phichain_chart::id::Identified;
use phichain_chart::serialization::{PhichainChart, SerializedLine};

fn evaluate_line(line: &mut SerializedLine) {
    let original_notes = line.notes.clone();
    for track in &line.curve_note_tracks {
        let find = |id| original_notes.iter().find(|note| note.id == id);
        if let (Some(from), Some(to)) = (find(track.from), find(track.to)) {
            line.notes.extend(
                generate_notes(from.data, to.data, &track.options)
                    .into_iter()
                    .map(Identified::new),
            );
        }
    }

    line.curve_note_tracks.clear();

    for child in &mut line.children {
        evaluate_line(child);
    }
}

/// Evaluate all curve note tracks and transform them into real notes
pub fn evaluate_curve_note_tracks(chart: PhichainChart) -> PhichainChart {
    let lines: Vec<_> = chart
        .lines
        .iter()
        .cloned()
        .map(|mut line| {
            evaluate_line(&mut line);
            line
        })
        .collect();

    PhichainChart { lines, ..chart }
}

#[cfg(test)]
mod tests {
    use super::*;
    use phichain_chart::beat;
    use phichain_chart::curve_note_track::{CurveNoteTrack, CurveNoteTrackOptions};
    use phichain_chart::id::{CurveNoteTrackId, Identified, LineId, NoteId};
    use phichain_chart::line::Line;
    use phichain_chart::note::{Note, NoteKind};
    use phichain_chart::serialization::SerializedLine;

    /// Curve note tracks reference notes by id within the original `notes` snapshot.
    /// When track A generates new notes and appends them, the array grows.
    /// Track B references unknown ids and should be skipped. Without snapshotting the
    /// original notes, track B would accidentally reference notes generated
    /// by track A, producing unwanted extra notes.
    #[test]
    fn later_track_should_not_reference_notes_generated_by_earlier_track() {
        // 2 original notes
        let notes = vec![
            Identified::new(Note::new(NoteKind::Tap, true, beat!(0), 0.0, 1.0)),
            Identified::new(Note::new(NoteKind::Tap, true, beat!(4), 100.0, 1.0)),
        ];

        // Track A: references the two original notes, valid, will generate notes and append them
        // Track B: references unknown ids, should be skipped
        let tracks = vec![
            CurveNoteTrack {
                id: CurveNoteTrackId::new(),
                from: notes[0].id,
                to: notes[1].id,
                options: CurveNoteTrackOptions::default(),
            },
            CurveNoteTrack {
                id: CurveNoteTrackId::new(),
                from: NoteId::new(),
                to: NoteId::new(),
                options: CurveNoteTrackOptions::default(),
            },
        ];

        let mut chart = PhichainChart::empty();
        chart.lines = vec![SerializedLine {
            line: Line {
                name: "test".to_string(),
            },
            id: LineId::new(),
            notes,
            events: vec![],
            children: vec![],
            curve_note_tracks: tracks,
        }];

        // Count notes generated by track A alone
        let track_a_notes = phichain_chart::curve_note_track::generate_notes(
            Note::new(NoteKind::Tap, true, beat!(0), 0.0, 1.0),
            Note::new(NoteKind::Tap, true, beat!(4), 100.0, 1.0),
            &CurveNoteTrackOptions::default(),
        );
        let expected_count = 2 + track_a_notes.len(); // original + track A only

        let result = evaluate_curve_note_tracks(chart);
        let actual_count = result.lines[0].notes.len();

        assert_eq!(
            actual_count, expected_count,
            "track B references unknown note ids and should be skipped, \
             but got {} notes instead of {}",
            actual_count, expected_count,
        );
    }
}
