use phichain_chart::curve_note_track::generate_notes;
use phichain_chart::serialization::{PhichainChart, SerializedLine};

fn evaluate_line(line: &mut SerializedLine) {
    let original_notes = line.notes.clone();
    for track in &line.curve_note_tracks {
        if let (Some(from), Some(to)) =
            (original_notes.get(track.from), original_notes.get(track.to))
        {
            line.notes
                .extend(generate_notes(*from, *to, &track.options));
        }
    }

    line.curve_note_tracks.clear();

    for child in &mut line.children {
        evaluate_line(child);
    }
}

/// Evaluate all curve note tracks and transform them into real notes
pub fn evaluate_curve_note_tracks(chart: PhichainChart) -> PhichainChart {
    let lines: Vec<_> = chart
        .lines
        .iter()
        .cloned()
        .map(|mut line| {
            evaluate_line(&mut line);
            line
        })
        .collect();

    PhichainChart { lines, ..chart }
}

#[cfg(test)]
mod tests {
    use super::*;
    use phichain_chart::beat;
    use phichain_chart::curve_note_track::{CurveNoteTrack, CurveNoteTrackOptions};
    use phichain_chart::line::Line;
    use phichain_chart::note::{Note, NoteKind};
    use phichain_chart::serialization::SerializedLine;

    /// Curve note tracks use indices into the original `notes` array.
    /// When track A generates new notes and appends them, the array grows.
    /// Track B's indices (from=2, to=50) are out of bounds in the original
    /// 2-element array and should be skipped. Without snapshotting the
    /// original notes, track B would accidentally reference notes generated
    /// by track A, producing unwanted extra notes.
    #[test]
    fn later_track_should_not_reference_notes_generated_by_earlier_track() {
        // 2 original notes at indices 0 and 1
        let notes = vec![
            Note::new(NoteKind::Tap, true, beat!(0), 0.0, 1.0),
            Note::new(NoteKind::Tap, true, beat!(4), 100.0, 1.0),
        ];

        // Track A: from=0, to=1, valid, will generate notes and append them
        // Track B: from=2, to=3, out of bounds in original notes, should be skipped
        let tracks = vec![
            CurveNoteTrack {
                from: 0,
                to: 1,
                options: CurveNoteTrackOptions::default(),
            },
            CurveNoteTrack {
                from: 2,
                to: 50,
                options: CurveNoteTrackOptions::default(),
            },
        ];

        let mut chart = PhichainChart::empty();
        chart.lines = vec![SerializedLine {
            line: Line {
                name: "test".to_string(),
            },
            notes,
            events: vec![],
            children: vec![],
            curve_note_tracks: tracks,
        }];

        // Count notes generated by track A alone
        let track_a_notes = phichain_chart::curve_note_track::generate_notes(
            Note::new(NoteKind::Tap, true, beat!(0), 0.0, 1.0),
            Note::new(NoteKind::Tap, true, beat!(4), 100.0, 1.0),
            &CurveNoteTrackOptions::default(),
        );
        let expected_count = 2 + track_a_notes.len(); // original + track A only

        let result = evaluate_curve_note_tracks(chart);
        let actual_count = result.lines[0].notes.len();

        assert_eq!(
            actual_count, expected_count,
            "track B (from=2, to=50) should be skipped because those indices are out of bounds \
             in the original notes, but got {} notes instead of {}",
            actual_count, expected_count,
        );
    }
}
