[package]
name = "phichain-format"
version = "0.1.0"
edition = "2024"

[dependencies]
phichain-chart = { path = "../phichain-chart" }
phichain-compiler = { path = "../phichain-compiler" }
anyhow = "1.0.89"
nalgebra = "0.34.1"
num = "0.4.3"
